server:
  port: ${PORT:8080}

base-url: /api
#
#spring:
#  application:
#    name: taskManager
#
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/changelog-master.yaml
#
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop

logging:
  level:
    root: INFO
