server:
  error:
    include-stacktrace: never

spring:
  # Настраиваем подключение к базе данных
  datasource:
    url: jdbc:h2:./taskManagerDB
    username: ""
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true

  # Настраиваем инструмент Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml # Указываем путь к основному файлу миграции

  # Настраиваем консоль Н2, чтобы можно было открыть её в браузере по указанному пути
  h2:
    console:
      enabled: true
      path: /h2console/ # Указываем путь, по которому будет открываться консоль
      settings:
        web-allow-others: true
