server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  # Настраиваем подключение к базе данных
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    show-sql: true

  # Настраиваем инструмент Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml # Указываем путь к основному файлу миграции
